#!/bin/bash

orig_folder="$(pwd)"

if [ ! -e biglinux-l18n ]; then
    git clone git@github.com:biglinux/biglinux-l18n.git
else
    cd biglinux-l18n
    git pull
    cd ..
fi

#for DIR in *;do
for DIR  in  "bigbashview" "bigcontrolcenter" "biglinux-config" "biglinux-driver-manager" "biglinux-grub-restore" "biglinux-hardware-detection" "biglinux-livecd" "biglinux-noise-reduction-pipewire" "biglinux-session-and-themes" "biglinux-updates-tweaks" "bigocrpdf" "big-store" "big-welcome" "calamares-biglinux" "debtap-mod" "sambasearch" "tts-biglinux" "waydroid-biglinux" ""; do

    if [ ! -e $DIR ]; then
        git clone https://github.com/biglinux/${DIR}.git
    else
        cd $DIR
        git pull
        cd ..
    fi

    [ ! -d "$DIR" ] && continue

    NAME="$DIR"

    [ -d "$DIR/$DIR" ] && DIR="$DIR/$DIR"
    [ ! -d biglinux-l18n/$NAME ] && mkdir -p biglinux-l18n/$NAME

    [ -e biglinux-l18n/$NAME/$NAME.pot ] && rm biglinux-l18n/$NAME/$NAME.pot
    echo -e "Directory:\t$DIR"

    for f in $(find $DIR -type f);do

        [ "$(file -b --mime-type $f)" != "text/x-shellscript" ] && continue
        [ $(grep 'git' <<< $f) ] && continue

        echo -e "\t\tFiles:\t$f"
        bash --dump-po-strings $f >> biglinux-l18n/$NAME/$NAME-tmp.pot

    done
    xgettext --package-name="$NAME" --no-location -L PO -o "biglinux-l18n/$NAME/$NAME.pot" -i "biglinux-l18n/$NAME/$NAME-tmp.pot"
    rm biglinux-l18n/$NAME/$NAME-tmp.pot
    
    if [ ! -e biglinux-l18n/$NAME/$NAME.pot ]; then
        rm -R biglinux-l18n/$NAME
    fi
    
done

cd "$orig_folder/biglinux-l18n"
git add --all
git commit -m "Automatic update .pot files"
git push

#rm locale/big-store.pot
#
#/usr/lib/python3.10/Tools/i18n/pygettext.py -o "locale/python.pot" *.py
#
#for f in $(find . \( -iname "*.sh.htm" -o -iname "*.sh" \));do
#    echo $f
#    bash --dump-po-strings $f >> locale/bash-files.pot
#done
#
#xgettext --package-name="big-store" --no-location -L PO -o "locale/bash.pot" -i "locale/bash-files.pot"
#rm locale/bash-files.pot
#msgcat locale/*.pot > locale/big-store.pot
#rm locale/bash.pot locale/python.pot
#
#for lang in {"en","es"};do
#  if [ -e "locale/$lang/LC_MESSAGES/big-store.po" ];then
#     msgmerge -o "locale/$lang/LC_MESSAGES/big-store.po" "locale/$lang/LC_MESSAGES/big-store.po" "locale/big-store.pot"
#  else
#     msginit --no-translator -l "$lang" -i "locale/big-store.pot" -o "locale/$lang/LC_MESSAGES/big-store.po"
#     sed -i 's|Content-Type: text/plain; charset=ASCII|Content-Type: text/plain; charset=utf-8|g' "locale/$lang/LC_MESSAGES/big-store.po"
#  fi
#done
#exit;
